#!/usr/bin/env bash
set -euo pipefail
echo "==> cargo fmt"
cargo fmt -- --check
echo "==> cargo test"
cargo test
echo "==> cargo clippy"
cargo clippy -- -D warnings
echo "==> cargo doc"
RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --document-private-items