//! Events received by the deliberation machine.

use super::state::DeliberationRole;

/// The outcome returned by a role after it has run.
#[derive(Clone, Debug, PartialEq)]
pub enum RoleResult {
    /// The role produced content that is acceptable.
    Accepted {
        /// The content generated by the role.
        content: String,
    },
    /// The role rejected the current attempt.
    Rejected {
        /// Human-readable explanation of why the content was rejected.
        reason: String,
    },
}

/// Events that drive the deliberation machine forward.
#[derive(Clone, Debug, PartialEq)]
pub enum DeliberationEvent {
    /// Bootstrap event — starts the pipeline from `Ready`.
    Start,
    /// A previously dispatched role has returned a result.
    RoleReturned {
        /// The role that produced this result.
        role: DeliberationRole,
        /// The outcome of the role's execution.
        result: RoleResult,
    },
}
