//! Events received by the deliberation machine.

use super::state::DeliberationRole;
use crate::machines::scheduler::FailureKind;

/// The outcome returned by a role after it has run.
#[derive(Clone, Debug, PartialEq)]
pub enum RoleResult {
    /// The role produced content that is acceptable.
    Accepted {
        /// The content generated by the role.
        content: String,
    },
    /// The role completed successfully but rejected the current content.
    ///
    /// For Producer, rejection is a terminal failure.
    /// For Critic, rejection is advisory — the machine routes to the Referee,
    /// which makes the final accept/reject decision.
    /// For Referee, rejection triggers a revision loop (if revisions remain).
    Rejected {
        /// Human-readable explanation of why the content was rejected.
        reason: String,
    },
    /// The role could not execute — an infrastructure or transport failure.
    ///
    /// Examples: timeout, provider unavailable, authentication error,
    /// malformed response, parsing failure.
    ///
    /// Unlike `Rejected`, this is always a terminal failure for every role.
    /// A `Failed` Referee result must not enter the revision loop.
    Failed {
        /// Machine-readable failure cause.
        kind: FailureKind,
        /// Human-readable description of the execution failure.
        reason: String,
    },
}

/// The typed outcome of validating accepted Producer output.
#[derive(Clone, Debug, PartialEq)]
pub enum ProducerValidationResult {
    /// The accepted Producer content satisfies semantic validation.
    Valid,
    /// The accepted Producer content failed semantic validation and may be
    /// retried while the supplied retry budget remains.
    Retry {
        /// Feedback to send to the next Producer attempt.
        feedback_reason: String,
        /// Maximum semantic validation retries allowed for this validation mode.
        max_retries: usize,
        /// Machine-readable terminal failure cause if retries are exhausted.
        failure_kind: FailureKind,
        /// Human-readable terminal failure reason if retries are exhausted.
        failure_reason: String,
    },
}

/// Events that drive the deliberation machine forward.
#[derive(Clone, Debug, PartialEq)]
pub enum DeliberationEvent {
    /// Bootstrap event — starts the pipeline from `Ready`.
    Start,
    /// A previously dispatched role has returned a result.
    RoleReturned {
        /// The role that produced this result.
        role: DeliberationRole,
        /// The outcome of the role's execution.
        result: RoleResult,
    },
    /// A Producer role call accepted content and reported artifact mutation
    /// metadata needed by producer semantic validation.
    ProducerAccepted {
        /// The accepted Producer content.
        content: String,
        /// Whether the Producer role call changed the artifact workspace.
        artifact_changed: bool,
    },
    /// Accepted Producer content has been semantically validated.
    ProducerValidationReturned {
        /// The accepted Producer content that was validated.
        content: String,
        /// The validation outcome.
        result: ProducerValidationResult,
    },
}
