//! Events received by the deliberation machine.

use super::state::DeliberationRole;

/// The outcome returned by a role after it has run.
#[derive(Clone, Debug, PartialEq)]
pub enum RoleResult {
    /// The role produced content that is acceptable.
    Accepted {
        /// The content generated by the role.
        content: String,
    },
    /// The role completed successfully but rejected the current content.
    ///
    /// For Producer and Critic, rejection is a terminal failure.
    /// For Referee, rejection triggers a revision loop (if revisions remain).
    Rejected {
        /// Human-readable explanation of why the content was rejected.
        reason: String,
    },
    /// The role could not execute — an infrastructure or transport failure.
    ///
    /// Examples: timeout, provider unavailable, authentication error,
    /// malformed response, parsing failure.
    ///
    /// Unlike `Rejected`, this is always a terminal failure for every role.
    /// A `Failed` Referee result must not enter the revision loop.
    Failed {
        /// Human-readable description of the execution failure.
        reason: String,
    },
}

/// Events that drive the deliberation machine forward.
#[derive(Clone, Debug, PartialEq)]
pub enum DeliberationEvent {
    /// Bootstrap event — starts the pipeline from `Ready`.
    Start,
    /// A previously dispatched role has returned a result.
    RoleReturned {
        /// The role that produced this result.
        role: DeliberationRole,
        /// The outcome of the role's execution.
        result: RoleResult,
    },
}
