//! Demo machine state types.
//!
//! The demo machine models a three-stage review pipeline: a producer generates
//! a response, a critic evaluates it, and a referee makes a final acceptance
//! decision. Each stage carries forward the outputs of all prior stages so that
//! later agents have full context.
//!
//! These types exist to demonstrate the machine pattern. They are not part of
//! the real Forge scheduler hierarchy.

/// The input to the demo pipeline. Everything the producer needs to know about
/// what it has been asked to do.
#[derive(Clone, Debug, PartialEq)]
pub struct Task {
    /// A short label identifying the task.
    pub name: String,
}

/// The raw output of the producer stage.
#[derive(Clone, Debug, PartialEq)]
pub struct ProducerResponse {
    /// The text generated by the producer.
    pub text: String,
}

/// The evaluation produced by the critic after reviewing the producer's output.
#[derive(Clone, Debug, PartialEq)]
pub struct CriticResponse {
    /// The critic's written evaluation.
    pub text: String,
}

/// The referee's final verdict after seeing both the producer and critic outputs.
#[derive(Clone, Debug, PartialEq)]
pub struct RefereeResponse {
    /// The referee's written verdict.
    pub text: String,
}

/// All three stage outputs collected into the final result.
///
/// `TaskResult` is what the caller receives when `run_machine` returns. It
/// holds a complete record of the pipeline execution so that callers can
/// inspect every stage's contribution.
#[derive(Clone, Debug, PartialEq)]
pub struct TaskResult {
    /// The original task that was submitted to the pipeline.
    pub task: Task,
    /// The output returned by the producer.
    pub producer_response: ProducerResponse,
    /// The critic's evaluation of the producer's output.
    pub critic_response: CriticResponse,
    /// The referee's final verdict.
    pub referee_response: RefereeResponse,
}

/// The lifecycle of the demo machine.
///
/// Each variant carries exactly what was accumulated up to that point. State
/// only moves forward; earlier stage outputs are always present in later states.
#[derive(Clone, Debug, PartialEq)]
pub enum DemoState {
    /// The pipeline has not started yet; only the original task is available.
    NotStarted {
        /// The task waiting to enter the pipeline.
        task: Task,
    },

    /// The producer has responded. The critic has not yet been called.
    PostProducer {
        /// The original task, carried forward for later stages.
        task: Task,
        /// The producer's output, ready to be sent to the critic.
        producer_response: ProducerResponse,
    },

    /// The critic has responded. The referee has not yet been called.
    PostCritic {
        /// The original task, carried forward for the referee.
        task: Task,
        /// The producer's output, carried forward for the referee.
        producer_response: ProducerResponse,
        /// The critic's evaluation, ready to be sent to the referee.
        critic_response: CriticResponse,
    },

    /// All three stages have completed. This is the terminal state; `output`
    /// will extract the `TaskResult` from here.
    PostReferee {
        /// The complete pipeline result, including all stage outputs.
        result: TaskResult,
    },
}
