//! Demo domain types.
//!
//! These types exist to demonstrate the machine pattern. They are not part of
//! the real Forge scheduler hierarchy.

/// The input to the demo pipeline. Everything the producer needs to know about
/// what it has been asked to do.
#[derive(Clone, Debug, PartialEq)]
pub struct Task {
    /// A short label identifying the task.
    pub name: String,
}

/// The raw output of the producer stage.
#[derive(Clone, Debug, PartialEq)]
pub struct ProducerResponse {
    /// The text generated by the producer.
    pub text: String,
}

/// The evaluation produced by the critic after reviewing the producer's output.
#[derive(Clone, Debug, PartialEq)]
pub struct CriticResponse {
    /// The critic's written evaluation.
    pub text: String,
}

/// The referee's final verdict after seeing both the producer and critic outputs.
#[derive(Clone, Debug, PartialEq)]
pub struct RefereeResponse {
    /// The referee's written verdict.
    pub text: String,
}

/// All three stage outputs collected into the final result.
///
/// `TaskResult` is what the caller receives when `run_machine` returns. It
/// holds a complete record of the pipeline execution so that callers can
/// inspect every stage's contribution.
#[derive(Clone, Debug, PartialEq)]
pub struct TaskResult {
    /// The original task that was submitted to the pipeline.
    pub task: Task,
    /// The output returned by the producer.
    pub producer_response: ProducerResponse,
    /// The critic's evaluation of the producer's output.
    pub critic_response: CriticResponse,
    /// The referee's final verdict.
    pub referee_response: RefereeResponse,
}
