//! Provider-backed role execution.
//!
//! `RoleRunner` owns one complete role round-trip: render prompt, call provider,
//! parse JSON, retry on protocol failure. The deliberation layer above sees only
//! `RoleRequest` in and `RoleResult` out.

use std::sync::{Arc, Mutex};

use crate::artifacts::{ArtifactRead, Workspace};
use crate::machines::deliberation::DeliberationContext;
use crate::machines::deliberation::{DeliberationRole, RevisionFeedback};
use crate::machines::scheduler::{FailureKind, NodeKind, TestPlanContext};
use crate::node_runner::planner::PlannerOutputProcessor;
use crate::providers::{ProviderClient, ProviderErrorKind, ProviderRequest, StructuredOutput};
use crate::roles::TargetView;
use crate::roles::policy::{
    PLANNER_GBNF_NO_WORK, PLANNER_GBNF_WITH_ROLES, PRODUCER_GBNF, PRODUCER_TOOL_GBNF,
    REVIEWER_TOOL_GBNF, ROLE_GBNF, RolePolicy, planner_protocol_schema_for, render_plugin_prompt,
};
use crate::services::extract_json_object;
use crate::telemetry::{TelemetryEvent, TelemetryRecord, TelemetrySink};
use crate::tools::{FileToolExecutor, looks_like_tool_request, parse_tool_request};

use super::parser::RoleResponseParser;
use super::prompt::{
    NodeReviewContract, RolePromptRender, render_role_prompt_with_test_plan_context,
    render_tool_section, role_subsource,
};
use super::protocol_state::ProtocolState;
use super::tooling::{RoleToolDispatcher, ToolDispatchOutcome, file_tool_policy_for_request};

#[cfg(test)]
use super::protocol_state::{MAX_PROTOCOL_RETRIES, MAX_READ_ONLY_TOOL_STEPS, MAX_TOOL_STEPS};

/// A read-only view of the artifact made available to role tool loops.
pub struct RoleToolContext {
    /// The artifact state the role may read from.
    ///
    /// In artifact Work this is the shared WorkAttempt workspace, so reviewer
    /// roles see producer writes directly.
    pub artifact_view: Box<dyn ArtifactRead>,
    /// Optional live workspace for artifact-producing Work attempts.
    pub writable_workspace: Option<Arc<Mutex<Workspace>>>,
}

impl std::fmt::Debug for RoleToolContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RoleToolContext")
            .field("artifact_view", &"<dyn ArtifactRead>")
            .finish()
    }
}

/// All inputs needed to execute one role invocation.
#[derive(Debug)]
pub struct RoleRequest {
    /// The role to invoke.
    pub role: DeliberationRole,
    /// The objective to pass to the role.
    pub objective: String,
    /// Structured prompt/tooling context for this role.
    pub context: DeliberationContext,
    /// Structured test-target planning context for this node.
    pub test_plan_context: TestPlanContext,
    /// Adapter-produced views of the target files for prompt context.
    ///
    /// Built by [`ProjectAdapter::build_target_views`] before the request is
    /// dispatched. The runner renders these verbatim and never inspects the
    /// artifact directly for target-state content.
    ///
    /// [`ProjectAdapter::build_target_views`]: crate::project::ProjectAdapter::build_target_views
    pub target_views: Vec<TargetView>,
    /// Content produced by the Producer. `None` when dispatching Producer.
    pub producer_content: Option<String>,
    /// Content produced by the Critic. `None` when dispatching Producer or Critic.
    pub critic_content: Option<String>,
    /// Accumulated Referee rejection feedback. Empty on the first pass.
    pub feedback: Vec<RevisionFeedback>,
    /// Whether the role is acting on a planner or worker node.
    /// Selects the matching node-kind-specific system prompt from the policy.
    pub node_kind: NodeKind,
    /// The worker role assigned to this Work node, if any.
    ///
    /// When set and present in [`RolePolicy::worker_role_policies`], selects
    /// that role's Producer/Critic/Referee prompts in place of the shared
    /// `worker_*_system` fields. Ignored for Plan nodes.
    pub worker_role: Option<String>,
    /// File tool context. When `Some`, the role may issue tool requests before
    /// returning a final result. When `None`, tool request JSON is still detected
    /// but produces an error observation rather than a real tool execution.
    pub tool_context: Option<RoleToolContext>,
}

/// The output of a completed role invocation.
pub struct RoleRunOutput {
    /// The semantic result returned by the role.
    pub result: RoleResult,
    /// Whether any file tool changed artifact state.
    pub artifact_changed: bool,
}

/// The outcome returned by a role after it has run.
#[derive(Clone, Debug, PartialEq)]
pub enum RoleResult {
    /// The role produced content that is acceptable.
    Accepted {
        /// The content generated by the role.
        content: String,
    },
    /// The role completed successfully but rejected the current content.
    Rejected {
        /// Human-readable explanation of why the content was rejected.
        reason: String,
    },
    /// The role could not execute — an infrastructure or transport failure.
    Failed {
        /// Machine-readable failure cause.
        kind: FailureKind,
        /// Human-readable description of the execution failure.
        reason: String,
    },
}

/// Execute one role invocation end-to-end and return its result.
pub trait RoleRunner {
    /// Run the role described by `request` and record protocol telemetry.
    fn run_role(&self, request: RoleRequest, telemetry: &dyn TelemetrySink) -> RoleRunOutput;
}

/// Provider-backed implementation of [`RoleRunner`].
///
/// Wraps a [`ProviderClient`] and owns all role-layer logic: prompt rendering,
/// provider invocation, JSON extraction/parsing, and protocol retry.
pub struct ProviderRoleRunner<P> {
    provider: P,
    max_tokens: u32,
    policy: RolePolicy,
}

impl<P> ProviderRoleRunner<P> {
    /// Wrap a provider in a new runner using the default token budget and default policy.
    pub fn new(provider: P) -> Self {
        Self {
            provider,
            max_tokens: MAX_RESPONSE_TOKENS,
            policy: RolePolicy::default(),
        }
    }

    /// Wrap a provider in a new runner with an explicit token budget and default policy.
    pub fn new_with_max_tokens(provider: P, max_tokens: u32) -> Self {
        Self {
            provider,
            max_tokens,
            policy: RolePolicy::default(),
        }
    }

    /// Wrap a provider in a new runner with an explicit policy and default token budget.
    pub fn new_with_policy(provider: P, policy: RolePolicy) -> Self {
        Self {
            provider,
            max_tokens: MAX_RESPONSE_TOKENS,
            policy,
        }
    }

    /// Replace the current policy, returning the updated runner.
    pub fn with_policy(mut self, policy: RolePolicy) -> Self {
        self.policy = policy;
        self
    }
}

/// Maximum number of tokens to request per provider call.
const MAX_RESPONSE_TOKENS: u32 = 1024;

/// Select the GBNF grammar constraining a role's output to its exact
/// response schema, rather than the generic JSON-object grammar.
///
/// The `Plan` Producer's grammar depends on `has_worker_roles`, matching the
/// footer text selected by [`planner_protocol_schema_for`] for the same
/// flag: an adapter with at least one worker role gets the grammar that
/// offers `kind: "work"`; an adapter with none never offers it, since there
/// would be no role to assign a work task to.
///
/// `tools_active` selects between the union tool-call-or-final-response
/// grammar and the final-response-only grammar. It is `true` only while the
/// role still has a tool loop and tool use remains permitted (`has_tools &&
/// proto.allow_tool_call()`); the Plan-node Producer never has tools, so it
/// always uses its single fixed grammar regardless of this flag.
fn select_grammar(
    node_kind: &NodeKind,
    role: &DeliberationRole,
    tools_active: bool,
    has_worker_roles: bool,
) -> &'static str {
    match role {
        DeliberationRole::Critic | DeliberationRole::Referee => {
            if tools_active {
                REVIEWER_TOOL_GBNF
            } else {
                ROLE_GBNF
            }
        }
        DeliberationRole::Producer => match node_kind {
            NodeKind::Work => {
                if tools_active {
                    PRODUCER_TOOL_GBNF
                } else {
                    PRODUCER_GBNF
                }
            }
            NodeKind::Plan => {
                if has_worker_roles {
                    PLANNER_GBNF_WITH_ROLES
                } else {
                    PLANNER_GBNF_NO_WORK
                }
            }
        },
    }
}

/// Result of parsing and structurally validating a Plan Producer response,
/// before the surrounding retry/telemetry handling in
/// [`ProviderRoleRunner::run_role`] decides what to do with it.
///
/// `ValidationFailed` and `ParseFailed` are kept distinct (rather than a
/// single failure string) because they map to different [`FailureKind`]s —
/// `PlannerValidationFailure` vs `ProtocolFailure` — when retries are
/// exhausted.
enum PlanParseOutcome {
    /// Canonical re-serialized JSON of the validated output.
    Success(String),
    /// The response parsed as JSON but failed structural validation.
    ValidationFailed(String),
    /// The response did not parse as the expected JSON shape at all.
    ParseFailed(String),
}

/// The prompt strings [`build_role_prompt`] composes for one role invocation.
pub(super) struct BuiltRolePrompt {
    /// The rendered prompt without the tool section appended.
    ///
    /// Kept separately from `base_prompt` because retry prompts (planner
    /// validation, must-read enforcement) are re-derived from this rather
    /// than from the tool-augmented prompt.
    pub(super) core_prompt: String,
    /// `core_prompt` with the tool section appended when `has_tools` is
    /// true; otherwise identical to `core_prompt`. This is the exact prompt
    /// sent to the model on the first attempt.
    pub(super) base_prompt: String,
}

/// Compose the system prompt and full user prompt for one role invocation,
/// exactly as [`ProviderRoleRunner::run_role`] does before entering its
/// provider round-trip loop.
///
/// Factored out so the prompt-preview CLI can render the same static
/// Identity/Context/Instructions/Constraints/tool-section content a real run
/// would produce, from a mock [`RoleRequest`], without duplicating the
/// system-prompt-selection and section-composition logic.
pub(super) fn build_role_prompt(
    request: &RoleRequest,
    policy: &RolePolicy,
    file_tool_policy: &crate::tools::FileToolPolicy,
    has_tools: bool,
) -> BuiltRolePrompt {
    let worker_role_policy = request
        .worker_role
        .as_deref()
        .and_then(|role| policy.worker_role_policies.get(role));

    // Plan Producer prompts use a fixed schema variant rebuilt from
    // `planner_producer_base` — see `planner_protocol_schema_for`.
    let system: String = match (&request.node_kind, &request.role) {
        (NodeKind::Plan, DeliberationRole::Producer) => format!(
            "{}\n\n{}",
            policy.planner_producer_base,
            planner_protocol_schema_for(!policy.worker_role_descriptions.is_empty())
        ),
        (NodeKind::Plan, DeliberationRole::Critic) => policy.planner_critic_system.clone(),
        (NodeKind::Plan, DeliberationRole::Referee) => policy.planner_referee_system.clone(),
        (NodeKind::Work, DeliberationRole::Producer) => worker_role_policy
            .map(|p| p.producer_system.clone())
            .unwrap_or_else(|| policy.worker_producer_system.clone()),
        (NodeKind::Work, DeliberationRole::Critic) => worker_role_policy
            .map(|p| p.critic_system.clone())
            .unwrap_or_else(|| policy.worker_critic_system.clone()),
        (NodeKind::Work, DeliberationRole::Referee) => worker_role_policy
            .map(|p| p.referee_system.clone())
            .unwrap_or_else(|| policy.worker_referee_system.clone()),
    };
    // The language plugin selected for this node's own target files
    // (see `select_plugin`) is composed here, per node, rather than
    // baked into `policy` — an adapter's declared plugins vary by
    // node, not by adapter, so a Rust node's prompt must not carry
    // Python guidance and vice versa.
    let system = match &request.context.plugin_prompt {
        Some(plugin) => format!("{system}\n\n{}", render_plugin_prompt(plugin)),
        None => system,
    };

    let review_contract = NodeReviewContract::for_role(
        &request.role,
        &request.node_kind,
        &request.context.target_files,
        &request.test_plan_context,
        has_tools,
    );
    // Only the Plan-node Producer sees the available worker roles — that
    // is the only kind that assigns roles to tasks. Decomposition tasks
    // have no roles, so the section is omitted from their prompt even
    // when the adapter defines worker roles.
    let worker_role_descriptions: &[(String, String)] =
        if matches!(request.node_kind, NodeKind::Plan)
            && matches!(request.role, DeliberationRole::Producer)
        {
            &policy.worker_role_descriptions
        } else {
            &[]
        };
    let core_prompt = render_role_prompt_with_test_plan_context(RolePromptRender {
        system: &system,
        role: &request.role,
        objective: &request.objective,
        context: &request.context,
        producer_content: request.producer_content.as_deref(),
        critic_content: request.critic_content.as_deref(),
        feedback: &request.feedback,
        target_views: &request.target_views,
        test_plan_context: &request.test_plan_context,
        review_contract: review_contract.as_ref(),
        worker_role_descriptions,
    });
    let base_prompt = if has_tools {
        format!("{core_prompt}\n\n{}", render_tool_section(file_tool_policy))
    } else {
        core_prompt.clone()
    };

    BuiltRolePrompt {
        core_prompt,
        base_prompt,
    }
}

impl<P: ProviderClient> RoleRunner for ProviderRoleRunner<P> {
    fn run_role(&self, request: RoleRequest, telemetry: &dyn TelemetrySink) -> RoleRunOutput {
        let subsource = role_subsource(&request.role);
        let has_tools = request.tool_context.is_some();

        let policy = file_tool_policy_for_request(
            &request.role,
            &request.node_kind,
            &request.context.target_files,
            &request.test_plan_context.required_validation_targets,
        );

        let BuiltRolePrompt {
            core_prompt,
            base_prompt,
        } = build_role_prompt(&request, &self.policy, &policy, has_tools);

        let executor: Option<FileToolExecutor> = request.tool_context.map(|ctx| {
            if let Some(workspace) = ctx.writable_workspace {
                FileToolExecutor::with_workspace(ctx.artifact_view, workspace, policy)
            } else {
                FileToolExecutor::with_policy(ctx.artifact_view, policy)
            }
        });

        // Completion pressure applies only to Work+Producer after a
        // successful mutation.
        let is_work_producer = request.node_kind == NodeKind::Work
            && matches!(request.role, DeliberationRole::Producer);
        // Decision pressure applies to Critic and Referee after bounded read-only tool use.
        let is_read_only_reviewer = matches!(
            request.role,
            DeliberationRole::Critic | DeliberationRole::Referee
        );
        // Work-node Critic and Referee must call read_file at least once before
        // accepting. list_files alone is insufficient — the model must inspect
        // actual file contents. This enforcement only applies when tools are
        // available; plan-node reviewers judge structure, not file contents.
        let requires_read_enforcement =
            request.node_kind == NodeKind::Work && is_read_only_reviewer && has_tools;

        let proto = ProtocolState::new(
            is_work_producer,
            is_read_only_reviewer,
            requires_read_enforcement,
        );
        let mut tools = RoleToolDispatcher::new(
            executor,
            proto,
            telemetry,
            subsource,
            core_prompt,
            base_prompt,
        );

        loop {
            telemetry.record(TelemetryRecord::new_with_subsource(
                "RoleMachine",
                subsource,
                TelemetryEvent::RolePromptRendered {
                    prompt: tools.current_prompt().to_owned(),
                    attempt_count: tools.current_attempt(),
                },
            ));

            // Recomputed each iteration: the model may keep calling tools for
            // as long as they remain permitted, so the union grammar (tool
            // call OR final response) stays active throughout the tool loop.
            // It narrows to the final-response-only grammar once tool use
            // ends (completion pressure, decision pressure, or no tools at
            // all), forcing the model to return its final response.
            let grammar = select_grammar(
                &request.node_kind,
                &request.role,
                has_tools && tools.allow_tool_call(),
                !self.policy.worker_role_descriptions.is_empty(),
            );

            let response = match self.provider.call(ProviderRequest {
                prompt: tools.current_prompt().to_owned(),
                max_tokens: self.max_tokens,
                output_schema: Some(StructuredOutput::Grammar(grammar.to_string())),
            }) {
                Ok(r) => r,
                Err(err) => {
                    let kind = match err.kind {
                        ProviderErrorKind::Retryable | ProviderErrorKind::Timeout => {
                            FailureKind::ProviderFailure
                        }
                        ProviderErrorKind::Terminal => FailureKind::ProviderTerminalFailure,
                    };
                    let artifact_changed = tools.artifact_changed();
                    return RoleRunOutput {
                        result: RoleResult::Failed {
                            kind,
                            reason: format!("provider error ({:?}): {}", err.kind, err.message),
                        },
                        artifact_changed,
                    };
                }
            };

            telemetry.record(TelemetryRecord::new_with_subsource(
                "RoleMachine",
                subsource,
                TelemetryEvent::ProviderResponseReceived {
                    raw_response: response.content.clone(),
                    attempt_count: tools.current_attempt(),
                },
            ));

            // Check for a tool request before trying to parse as a role result.
            // When the response looks like a tool-call attempt (carries a
            // "tool" field) but fails to parse, capture the reason so a
            // subsequent role-response parse failure can report the real
            // cause instead of a misleading "could not be parsed" message.
            let role_response = RoleResponseParser::new(&response.content);
            let trimmed = role_response.text();
            let mut tool_call_error: Option<String> = None;
            if let Some(json_str) = extract_json_object(trimmed) {
                match parse_tool_request(json_str) {
                    Ok(tool_req) => match tools.dispatch_tool_step(tool_req, &response.content) {
                        ToolDispatchOutcome::Continue => continue,
                        ToolDispatchOutcome::Fail(result) => {
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result,
                                artifact_changed,
                            };
                        }
                    },
                    Err(e) if looks_like_tool_request(json_str) => {
                        tool_call_error = Some(e);
                    }
                    Err(_) => {}
                }
            }

            // Not a tool request — select parser based on role and node kind.
            if matches!(request.node_kind, NodeKind::Plan)
                && matches!(request.role, DeliberationRole::Producer)
            {
                let processor = PlannerOutputProcessor::new(&self.policy.worker_role_descriptions);
                let planner_schema =
                    planner_protocol_schema_for(!self.policy.worker_role_descriptions.is_empty());
                // Direct PlannerOutput path: no status/content wrapper.
                let outcome = match processor.parse_response(&response.content) {
                    Ok(out) => match processor.validate(&out) {
                        Ok(()) => PlanParseOutcome::Success(
                            serde_json::to_string(&out)
                                .expect("validated PlannerOutput must serialize"),
                        ),
                        Err(e) => PlanParseOutcome::ValidationFailed(format!(
                            "planner output validation failed: {e}"
                        )),
                    },
                    Err(e) => PlanParseOutcome::ParseFailed(e),
                };
                match outcome {
                    PlanParseOutcome::Success(canonical) => {
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseSucceeded {
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        let artifact_changed = tools.artifact_changed();
                        return RoleRunOutput {
                            result: RoleResult::Accepted { content: canonical },
                            artifact_changed,
                        };
                    }
                    PlanParseOutcome::ValidationFailed(err) => {
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseFailed {
                                raw_response: response.content.clone(),
                                parse_error: err.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        if !tools.allow_model_call() {
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Failed {
                                    kind: FailureKind::PlannerValidationFailure,
                                    reason: err,
                                },
                                artifact_changed,
                            };
                        }
                        tools.record_protocol_failure();
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ProtocolRetry {
                                parse_error: err.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        tools.render_planner_retry_prompt(&err, &response.content, planner_schema);
                    }
                    PlanParseOutcome::ParseFailed(parse_error) => {
                        let effective_error = match &tool_call_error {
                            Some(te) => format!("malformed tool call: {te}"),
                            None => parse_error,
                        };
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseFailed {
                                raw_response: response.content.clone(),
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        if !tools.allow_model_call() {
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Failed {
                                    kind: FailureKind::ProtocolFailure,
                                    reason: effective_error,
                                },
                                artifact_changed,
                            };
                        }
                        tools.record_protocol_failure();
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ProtocolRetry {
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        tools.render_planner_retry_prompt(
                            &effective_error,
                            &response.content,
                            planner_schema,
                        );
                    }
                }
            } else {
                // Work-node Producer uses the summary-only schema and never
                // rejects; Critic and Referee use the status/content
                // accept-or-reject schema.
                let parse_result = if is_work_producer {
                    role_response.parse_producer_summary_response()
                } else {
                    role_response.parse_role_response()
                };
                match parse_result {
                    Ok(result) => {
                        // Enforce that Work-node reviewers read at least one file before
                        // accepting. list_files alone is not sufficient — the reviewer
                        // must inspect actual file contents to verify the objective.
                        if tools.reviewer_accepted_without_reading()
                            && matches!(result, RoleResult::Accepted { .. })
                        {
                            let attempt_note = if tools.read_file_attempted() == 0 {
                                "no read_file was attempted".to_string()
                            } else {
                                format!(
                                    "{} read_file attempt(s) were made but all failed",
                                    tools.read_file_attempted()
                                )
                            };
                            let parse_error = format!(
                                "{subsource} accepted without successfully reading any file \
                                ({attempt_note}); use read_file with a valid relative path \
                                to inspect the work before deciding"
                            );
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ParseFailed {
                                    raw_response: response.content.clone(),
                                    parse_error: parse_error.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            // When tools are blocked (decision or completion pressure active)
                            // there is no point issuing a must-read retry prompt — the model
                            // cannot call tools and would only generate further protocol errors.
                            // Fail directly with a clear reason in that case.
                            if tools.reviewer_accept_must_fail_immediately() {
                                let artifact_changed = tools.artifact_changed();
                                return RoleRunOutput {
                                    result: RoleResult::Failed {
                                        kind: FailureKind::ProtocolFailure,
                                        reason: parse_error,
                                    },
                                    artifact_changed,
                                };
                            }
                            tools.record_protocol_failure();
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ProtocolRetry {
                                    parse_error: parse_error.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            tools.render_reviewer_must_read_prompt(&parse_error);
                            continue;
                        }
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseSucceeded {
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        let artifact_changed = tools.artifact_changed();
                        return RoleRunOutput {
                            result,
                            artifact_changed,
                        };
                    }
                    Err(parse_error) => {
                        // Replace the generic role-response parse error with the
                        // tool-call parse error when the response was actually an
                        // attempted (but malformed) tool call — e.g. an echoed
                        // tool-section placeholder ($TARGET_FILE / $FILE_CONTENT)
                        // or a tool call with an invalid field.
                        let effective_error: String = match &tool_call_error {
                            Some(te) => format!("malformed tool call: {te}"),
                            None => parse_error,
                        };
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseFailed {
                                raw_response: response.content.clone(),
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        if !tools.allow_model_call() {
                            // A parse failure after completion pressure means the
                            // write was already recorded but the model could not
                            // confirm it. Label the reason so the node-runner
                            // classifier can treat it as Retry rather than Terminal.
                            let terminal_reason = if !tools.allow_tool_call() {
                                format!("protocol failure after write: {effective_error}")
                            } else {
                                effective_error
                            };
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Failed {
                                    kind: FailureKind::ProtocolFailure,
                                    reason: terminal_reason,
                                },
                                artifact_changed,
                            };
                        }
                        tools.record_protocol_failure();
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ProtocolRetry {
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        tools.render_role_retry_prompt(
                            &effective_error,
                            &response.content,
                            is_work_producer,
                        );
                    }
                }
            }
        }
    }
}

#[cfg(test)]
#[path = "runner_tests/mod.rs"]
mod tests;
