//! Provider-backed role execution.
//!
//! `RoleRunner` owns one complete role round-trip: render prompt, call provider,
//! parse JSON, retry on protocol failure. The deliberation layer above sees only
//! `RoleRequest` in and `RoleResult` out.

use std::cell::RefCell;
use std::rc::Rc;

use crate::artifacts::{ArtifactRead, Workspace};
use crate::machines::deliberation::DeliberationContext;
use crate::machines::deliberation::{DeliberationRole, RevisionFeedback};
use crate::machines::scheduler::{FailureKind, NodeKind, TestPlanContext};
use crate::node_runner::planner::PlannerOutputProcessor;
use crate::providers::{ProviderClient, ProviderErrorKind, ProviderRequest, StructuredOutput};
use crate::roles::TargetView;
use crate::roles::policy::{
    PLANNER_GBNF, PLANNER_NO_OPERATION_GBNF, PLANNER_PROTOCOL_FOOTER_WITH_OPERATION, PRODUCER_GBNF,
    PRODUCER_TOOL_GBNF, REVIEWER_TOOL_GBNF, ROLE_GBNF, RolePolicy,
};
use crate::services::extract_json_object;
use crate::telemetry::{TelemetryEvent, TelemetryRecord, TelemetrySink};
use crate::tools::{FileToolExecutor, looks_like_tool_request, parse_tool_request};

use super::parser::RoleResponseParser;
use super::prompt::{
    NodeReviewContract, RolePromptRender, render_role_prompt_with_test_plan_context,
    render_tool_section, role_subsource,
};
use super::protocol_state::ProtocolState;
use super::tooling::{RoleToolDispatcher, ToolDispatchOutcome, file_tool_policy_for_request};

#[cfg(test)]
use super::parser::MIN_CONTENT_LENGTH;
#[cfg(test)]
use super::prompt::format_tool_observation;
#[cfg(test)]
use super::protocol_state::{MAX_PROTOCOL_RETRIES, MAX_READ_ONLY_TOOL_STEPS, MAX_TOOL_STEPS};
#[cfg(test)]
use crate::tools::FileToolResponse;

/// A read-only view of the artifact made available to role tool loops.
pub struct RoleToolContext {
    /// The artifact state the role may read from.
    ///
    /// In artifact Work this is the shared WorkAttempt workspace, so reviewer
    /// roles see producer writes directly.
    pub artifact_view: Box<dyn ArtifactRead>,
    /// Optional live workspace for artifact-producing Work attempts.
    pub writable_workspace: Option<Rc<RefCell<Workspace>>>,
}

impl std::fmt::Debug for RoleToolContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RoleToolContext")
            .field("artifact_view", &"<dyn ArtifactRead>")
            .finish()
    }
}

/// All inputs needed to execute one role invocation.
#[derive(Debug)]
pub struct RoleRequest {
    /// The role to invoke.
    pub role: DeliberationRole,
    /// The objective to pass to the role.
    pub objective: String,
    /// Structured prompt/tooling context for this role.
    pub context: DeliberationContext,
    /// Structured test-target planning context for this node.
    pub test_plan_context: TestPlanContext,
    /// Adapter-produced views of the target files for prompt context.
    ///
    /// Built by [`ProjectAdapter::build_target_views`] before the request is
    /// dispatched. The runner renders these verbatim and never inspects the
    /// artifact directly for target-state content.
    ///
    /// [`ProjectAdapter::build_target_views`]: crate::project::ProjectAdapter::build_target_views
    pub target_views: Vec<TargetView>,
    /// Content produced by the Producer. `None` when dispatching Producer.
    pub producer_content: Option<String>,
    /// Content produced by the Critic. `None` when dispatching Producer or Critic.
    pub critic_content: Option<String>,
    /// Accumulated Referee rejection feedback. Empty on the first pass.
    pub feedback: Vec<RevisionFeedback>,
    /// Whether the role is acting on a planner or worker node.
    /// Selects the matching node-kind-specific system prompt from the policy.
    pub node_kind: NodeKind,
    /// File tool context. When `Some`, the role may issue tool requests before
    /// returning a final result. When `None`, tool request JSON is still detected
    /// but produces an error observation rather than a real tool execution.
    pub tool_context: Option<RoleToolContext>,
}

/// The output of a completed role invocation.
pub struct RoleRunOutput {
    /// The semantic result returned by the role.
    pub result: RoleResult,
    /// Whether any file tool changed artifact state.
    pub artifact_changed: bool,
}

/// The outcome returned by a role after it has run.
#[derive(Clone, Debug, PartialEq)]
pub enum RoleResult {
    /// The role produced content that is acceptable.
    Accepted {
        /// The content generated by the role.
        content: String,
    },
    /// The role completed successfully but rejected the current content.
    Rejected {
        /// Human-readable explanation of why the content was rejected.
        reason: String,
    },
    /// The role could not execute — an infrastructure or transport failure.
    Failed {
        /// Machine-readable failure cause.
        kind: FailureKind,
        /// Human-readable description of the execution failure.
        reason: String,
    },
}

/// Execute one role invocation end-to-end and return its result.
pub trait RoleRunner {
    /// Run the role described by `request` and record protocol telemetry.
    fn run_role(&self, request: RoleRequest, telemetry: &dyn TelemetrySink) -> RoleRunOutput;
}

/// Provider-backed implementation of [`RoleRunner`].
///
/// Wraps a [`ProviderClient`] and owns all role-layer logic: prompt rendering,
/// provider invocation, JSON extraction/parsing, and protocol retry.
pub struct ProviderRoleRunner<P> {
    provider: P,
    max_tokens: u32,
    policy: RolePolicy,
}

impl<P> ProviderRoleRunner<P> {
    /// Wrap a provider in a new runner using the default token budget and default policy.
    pub fn new(provider: P) -> Self {
        Self {
            provider,
            max_tokens: MAX_RESPONSE_TOKENS,
            policy: RolePolicy::default(),
        }
    }

    /// Wrap a provider in a new runner with an explicit token budget and default policy.
    pub fn new_with_max_tokens(provider: P, max_tokens: u32) -> Self {
        Self {
            provider,
            max_tokens,
            policy: RolePolicy::default(),
        }
    }

    /// Wrap a provider in a new runner with an explicit policy and default token budget.
    pub fn new_with_policy(provider: P, policy: RolePolicy) -> Self {
        Self {
            provider,
            max_tokens: MAX_RESPONSE_TOKENS,
            policy,
        }
    }

    /// Replace the current policy, returning the updated runner.
    pub fn with_policy(mut self, policy: RolePolicy) -> Self {
        self.policy = policy;
        self
    }
}

/// Maximum number of tokens to request per provider call.
const MAX_RESPONSE_TOKENS: u32 = 1024;

/// Select the GBNF grammar constraining a role's output to its exact
/// response schema, rather than the generic JSON-object grammar.
///
/// The Plan-node Producer schema depends on whether the active adapter's
/// task schema carries an `operation` field — inferred from
/// `planner_protocol_schema`, the same field the retry prompt already uses
/// to show the model the correct schema variant.
///
/// `tools_active` selects between the union tool-call-or-final-response
/// grammar and the final-response-only grammar. It is `true` only while the
/// role still has a tool loop and tool use remains permitted (`has_tools &&
/// proto.allow_tool_call()`); the Plan-node Producer never has tools, so it
/// always uses its single fixed grammar regardless of this flag.
fn select_grammar(
    node_kind: &NodeKind,
    role: &DeliberationRole,
    policy: &RolePolicy,
    tools_active: bool,
) -> &'static str {
    match role {
        DeliberationRole::Critic | DeliberationRole::Referee => {
            if tools_active {
                REVIEWER_TOOL_GBNF
            } else {
                ROLE_GBNF
            }
        }
        DeliberationRole::Producer => match node_kind {
            NodeKind::Work => {
                if tools_active {
                    PRODUCER_TOOL_GBNF
                } else {
                    PRODUCER_GBNF
                }
            }
            NodeKind::Plan => {
                if policy.planner_protocol_schema == PLANNER_PROTOCOL_FOOTER_WITH_OPERATION {
                    PLANNER_GBNF
                } else {
                    PLANNER_NO_OPERATION_GBNF
                }
            }
        },
    }
}

impl<P: ProviderClient> RoleRunner for ProviderRoleRunner<P> {
    fn run_role(&self, request: RoleRequest, telemetry: &dyn TelemetrySink) -> RoleRunOutput {
        let subsource = role_subsource(&request.role);
        let has_tools = request.tool_context.is_some();

        let policy = file_tool_policy_for_request(
            &request.role,
            &request.node_kind,
            &request.context.target_files,
        );

        let system = match (&request.node_kind, &request.role) {
            (NodeKind::Plan, DeliberationRole::Producer) => &self.policy.planner_producer_system,
            (NodeKind::Plan, DeliberationRole::Critic) => &self.policy.planner_critic_system,
            (NodeKind::Plan, DeliberationRole::Referee) => &self.policy.planner_referee_system,
            (NodeKind::Work, DeliberationRole::Producer) => &self.policy.worker_producer_system,
            (NodeKind::Work, DeliberationRole::Critic) => &self.policy.worker_critic_system,
            (NodeKind::Work, DeliberationRole::Referee) => &self.policy.worker_referee_system,
        };

        let review_contract = NodeReviewContract::for_role(
            &request.role,
            &request.node_kind,
            &request.context.target_files,
            &request.test_plan_context,
            has_tools,
        );
        let core_prompt = render_role_prompt_with_test_plan_context(RolePromptRender {
            system,
            role: &request.role,
            objective: &request.objective,
            context: &request.context,
            producer_content: request.producer_content.as_deref(),
            critic_content: request.critic_content.as_deref(),
            feedback: &request.feedback,
            target_views: &request.target_views,
            test_plan_context: &request.test_plan_context,
            review_contract: review_contract.as_ref(),
        });
        let core_prompt = match &self.policy.language_guidance {
            Some(guidance) => format!("{core_prompt}\n\nLanguage guidance:\n{guidance}"),
            None => core_prompt,
        };
        let core_prompt = match &self.policy.language_constraints {
            Some(constraints) => {
                format!("{core_prompt}\n\nLanguage constraints:\n{constraints}")
            }
            None => core_prompt,
        };
        let base_prompt = if has_tools {
            format!("{core_prompt}\n\n{}", render_tool_section(&policy))
        } else {
            core_prompt.clone()
        };

        let executor: Option<FileToolExecutor> = request.tool_context.map(|ctx| {
            if let Some(workspace) = ctx.writable_workspace {
                FileToolExecutor::with_workspace(ctx.artifact_view, workspace, policy)
            } else {
                FileToolExecutor::with_policy(ctx.artifact_view, policy)
            }
        });

        // Completion pressure applies only to Work+Producer after a successful mutation.
        let is_work_producer = request.node_kind == NodeKind::Work
            && matches!(request.role, DeliberationRole::Producer);
        // Decision pressure applies to Critic and Referee after bounded read-only tool use.
        let is_read_only_reviewer = matches!(
            request.role,
            DeliberationRole::Critic | DeliberationRole::Referee
        );
        // Work-node Critic and Referee must call read_file at least once before
        // accepting. list_files alone is insufficient — the model must inspect
        // actual file contents. This enforcement only applies when tools are
        // available; plan-node reviewers judge structure, not file contents.
        let requires_read_enforcement =
            request.node_kind == NodeKind::Work && is_read_only_reviewer && has_tools;

        let proto = ProtocolState::new(
            is_work_producer,
            is_read_only_reviewer,
            requires_read_enforcement,
        );
        let mut tools = RoleToolDispatcher::new(
            executor,
            proto,
            telemetry,
            subsource,
            core_prompt,
            base_prompt,
        );

        loop {
            telemetry.record(TelemetryRecord::new_with_subsource(
                "RoleMachine",
                subsource,
                TelemetryEvent::RolePromptRendered {
                    prompt: tools.current_prompt().to_owned(),
                    attempt_count: tools.current_attempt(),
                },
            ));

            // Recomputed each iteration: the model may keep calling tools for
            // as long as they remain permitted, so the union grammar (tool
            // call OR final response) stays active throughout the tool loop.
            // It narrows to the final-response-only grammar once tool use
            // ends (completion pressure, decision pressure, or no tools at
            // all), forcing the model to return its final response.
            let grammar = select_grammar(
                &request.node_kind,
                &request.role,
                &self.policy,
                has_tools && tools.allow_tool_call(),
            );

            let response = match self.provider.call(ProviderRequest {
                prompt: tools.current_prompt().to_owned(),
                max_tokens: self.max_tokens,
                output_schema: Some(StructuredOutput::Grammar(grammar.to_string())),
            }) {
                Ok(r) => r,
                Err(err) => {
                    let kind = match err.kind {
                        ProviderErrorKind::Retryable | ProviderErrorKind::Timeout => {
                            FailureKind::ProviderFailure
                        }
                        ProviderErrorKind::Terminal => FailureKind::ProviderTerminalFailure,
                    };
                    let artifact_changed = tools.artifact_changed();
                    return RoleRunOutput {
                        result: RoleResult::Failed {
                            kind,
                            reason: format!("provider error ({:?}): {}", err.kind, err.message),
                        },
                        artifact_changed,
                    };
                }
            };

            telemetry.record(TelemetryRecord::new_with_subsource(
                "RoleMachine",
                subsource,
                TelemetryEvent::ProviderResponseReceived {
                    raw_response: response.content.clone(),
                    attempt_count: tools.current_attempt(),
                },
            ));

            // Check for a tool request before trying to parse as a role result.
            // When the response looks like a tool-call attempt (carries a
            // "tool" field) but fails to parse, capture the reason so a
            // subsequent role-response parse failure can report the real
            // cause instead of a misleading "could not be parsed" message.
            let role_response = RoleResponseParser::new(&response.content);
            let trimmed = role_response.text();
            let mut tool_call_error: Option<String> = None;
            if let Some(json_str) = extract_json_object(trimmed) {
                match parse_tool_request(json_str) {
                    Ok(tool_req) => match tools.dispatch_tool_step(tool_req, &response.content) {
                        ToolDispatchOutcome::Continue => continue,
                        ToolDispatchOutcome::Fail(result) => {
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result,
                                artifact_changed,
                            };
                        }
                    },
                    Err(e) if looks_like_tool_request(json_str) => {
                        tool_call_error = Some(e);
                    }
                    Err(_) => {}
                }
            }

            // Not a tool request — select parser based on role and node kind.
            if request.node_kind == NodeKind::Plan
                && matches!(request.role, DeliberationRole::Producer)
            {
                let no_required_test_targets = |_: &[String]| Vec::new();
                let processor = PlannerOutputProcessor::new(
                    &request.objective,
                    std::iter::empty::<&str>(),
                    &no_required_test_targets,
                );
                // Direct PlannerOutput path: no status/content wrapper.
                match processor.parse_response(&response.content) {
                    Ok(planner_out) => match processor.validate_structure(&planner_out) {
                        Ok(()) => {
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ParseSucceeded {
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            let canonical = serde_json::to_string(&planner_out)
                                .expect("validated PlannerOutput must serialize");
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Accepted { content: canonical },
                                artifact_changed,
                            };
                        }
                        Err(e) => {
                            let err = format!("planner output validation failed: {e}");
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ParseFailed {
                                    raw_response: response.content.clone(),
                                    parse_error: err.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            if !tools.allow_model_call() {
                                let artifact_changed = tools.artifact_changed();
                                return RoleRunOutput {
                                    result: RoleResult::Failed {
                                        kind: FailureKind::PlannerValidationFailure,
                                        reason: err,
                                    },
                                    artifact_changed,
                                };
                            }
                            tools.record_protocol_failure();
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ProtocolRetry {
                                    parse_error: err.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            tools.render_planner_retry_prompt(
                                &err,
                                &response.content,
                                &self.policy.planner_protocol_schema,
                            );
                        }
                    },
                    Err(parse_error) => {
                        let effective_error = match &tool_call_error {
                            Some(te) => format!("malformed tool call: {te}"),
                            None => parse_error,
                        };
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseFailed {
                                raw_response: response.content.clone(),
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        if !tools.allow_model_call() {
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Failed {
                                    kind: FailureKind::ProtocolFailure,
                                    reason: effective_error,
                                },
                                artifact_changed,
                            };
                        }
                        tools.record_protocol_failure();
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ProtocolRetry {
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        tools.render_planner_retry_prompt(
                            &effective_error,
                            &response.content,
                            &self.policy.planner_protocol_schema,
                        );
                    }
                }
            } else {
                // Work-node Producer uses the summary-only schema and never
                // rejects; Critic and Referee use the status/content
                // accept-or-reject schema.
                let parse_result = if is_work_producer {
                    role_response.parse_producer_summary_response()
                } else {
                    role_response.parse_role_response()
                };
                match parse_result {
                    Ok(result) => {
                        // Enforce that Work-node reviewers read at least one file before
                        // accepting. list_files alone is not sufficient — the reviewer
                        // must inspect actual file contents to verify the objective.
                        if tools.reviewer_accepted_without_reading()
                            && matches!(result, RoleResult::Accepted { .. })
                        {
                            let attempt_note = if tools.read_file_attempted() == 0 {
                                "no read_file was attempted".to_string()
                            } else {
                                format!(
                                    "{} read_file attempt(s) were made but all failed",
                                    tools.read_file_attempted()
                                )
                            };
                            let parse_error = format!(
                                "{subsource} accepted without successfully reading any file \
                                ({attempt_note}); use read_file with a valid relative path \
                                to inspect the work before deciding"
                            );
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ParseFailed {
                                    raw_response: response.content.clone(),
                                    parse_error: parse_error.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            // When tools are blocked (decision or completion pressure active)
                            // there is no point issuing a must-read retry prompt — the model
                            // cannot call tools and would only generate further protocol errors.
                            // Fail directly with a clear reason in that case.
                            if tools.reviewer_accept_must_fail_immediately() {
                                let artifact_changed = tools.artifact_changed();
                                return RoleRunOutput {
                                    result: RoleResult::Failed {
                                        kind: FailureKind::ProtocolFailure,
                                        reason: parse_error,
                                    },
                                    artifact_changed,
                                };
                            }
                            tools.record_protocol_failure();
                            telemetry.record(TelemetryRecord::new_with_subsource(
                                "RoleMachine",
                                subsource,
                                TelemetryEvent::ProtocolRetry {
                                    parse_error: parse_error.clone(),
                                    attempt_count: tools.current_attempt(),
                                },
                            ));
                            tools.render_reviewer_must_read_prompt(&parse_error);
                            continue;
                        }
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseSucceeded {
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        let artifact_changed = tools.artifact_changed();
                        return RoleRunOutput {
                            result,
                            artifact_changed,
                        };
                    }
                    Err(parse_error) => {
                        // Replace the generic role-response parse error with the
                        // tool-call parse error when the response was actually an
                        // attempted (but malformed) tool call — e.g. an echoed
                        // tool-section placeholder ($TARGET_FILE / $FILE_CONTENT)
                        // or a tool call with an invalid field.
                        let effective_error: String = match &tool_call_error {
                            Some(te) => format!("malformed tool call: {te}"),
                            None => parse_error,
                        };
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ParseFailed {
                                raw_response: response.content.clone(),
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        if !tools.allow_model_call() {
                            // A parse failure after completion pressure means the
                            // write was already recorded but the model could not
                            // confirm it. Label the reason so the node-runner
                            // classifier can treat it as Retry rather than Terminal.
                            let terminal_reason = if !tools.allow_tool_call() {
                                format!("protocol failure after write: {effective_error}")
                            } else {
                                effective_error
                            };
                            let artifact_changed = tools.artifact_changed();
                            return RoleRunOutput {
                                result: RoleResult::Failed {
                                    kind: FailureKind::ProtocolFailure,
                                    reason: terminal_reason,
                                },
                                artifact_changed,
                            };
                        }
                        tools.record_protocol_failure();
                        telemetry.record(TelemetryRecord::new_with_subsource(
                            "RoleMachine",
                            subsource,
                            TelemetryEvent::ProtocolRetry {
                                parse_error: effective_error.clone(),
                                attempt_count: tools.current_attempt(),
                            },
                        ));
                        tools.render_role_retry_prompt(
                            &effective_error,
                            &response.content,
                            is_work_producer,
                        );
                    }
                }
            }
        }
    }
}

#[cfg(test)]
#[path = "runner_tests/mod.rs"]
mod tests;
